FROM postgres:15-alpine

# Copier le script d'initialisation
COPY init_db.sql /docker-entrypoint-initdb.d/

# Variables d'environnement
ENV POSTGRES_DB=radius
ENV POSTGRES_USER=radius
ENV POSTGRES_PASSWORD=radpass

# Exposer le port PostgreSQL
EXPOSE 5432
