FROM ubuntu/bind9:latest

# Installer dig et nslookup
RUN apt-get update && apt-get install -y dnsutils && rm -rf /var/lib/apt/lists/*

# Copie des fichiers de configuration
COPY /config/named.conf.options /etc/bind/named.conf.options
COPY /config/named.conf.local /etc/bind/named.conf.local
COPY /config/db.lab.local /etc/bind/db.lab.local

# Permet l'exécution
CMD ["/usr/sbin/named", "-g", "-c", "/etc/bind/named.conf", "-u", "bind"]